openapi: 3.0.3
info:
  title: Recommend
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/admin/login:
    post:
      summary: ''
      operationId: postApiAdminLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 191 characters.'
                  example: adolphus.schmeler@example.com
                password:
                  type: string
                  description: ''
                  example: quae
              required:
                - email
                - password
      security: []
  /api/admin/logout:
    post:
      summary: ''
      operationId: postApiAdminLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/admin/products:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 2 characters. Must not be greater than 191 characters.'
                  example: vrcnonatnprgthiimpnjakmbt
                price:
                  type: number
                  description: ''
                  example: 208734.654328
              required:
                - name
                - price
      security: []
  '/api/admin/products/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  /api/tokens/create:
    post:
      summary: ''
      operationId: postApiTokensCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/register:
    post:
      summary: ''
      operationId: postApiUserRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aliquam
                email:
                  type: string
                  description: ''
                  example: koss.nicholas@example.com
                password:
                  type: string
                  description: ''
                  example: 'ixt#(s#aAq$w'
              required:
                - name
                - email
                - password
      security: []
  /api/user/login:
    post:
      summary: ''
      operationId: postApiUserLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: colin29@example.net
                password:
                  type: string
                  description: ''
                  example: 'bf2{+EL#GH@eG"4'
              required:
                - email
                - password
      security: []
  /api/user/logout:
    post:
      summary: ''
      operationId: postApiUserLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/products:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/user/products/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user/cart/add:
    post:
      summary: ''
      operationId: postApiUserCartAdd
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: array
                  description: 'Must be at least 1 character.'
                  example:
                    - tenkgbibitncvtfnewszhitvbfpdvswweuxyafhwjelkptmthutkgmiuwpqhrvgceqidjth
                  items:
                    type: string
                quantity:
                  type: array
                  description: 'Must be at least 1.'
                  example:
                    - 40
                  items:
                    type: number
              required:
                - id
                - quantity
      security: []
  /api/user/cart/show:
    get:
      summary: ''
      operationId: getApiUserCartShow
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/user/cart/empty:
    post:
      summary: ''
      operationId: postApiUserCartEmpty
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/user/checkout:
    post:
      summary: ''
      operationId: postApiUserCheckout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
